

CREATE TABLE Users(
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE Buses(
    id INT AUTO_INCREMENT PRIMARY KEY,
    busNumber VARCHAR(50) UNIQUE NOT NULL,
    totalSeats Int NOT NULL,
    availableSeats INT NOT NULL
);
-- BUS LOGIC IS DONE 
-- NOW LET'S START WITH BOOKING TABLE WHO BOOKS WHICH BUS 
CREATE TABLE BusBookings(
    id INT AUTO_INCREMENT PRIMARY KEY,
    seatNumber INT NOT NULL
);
-- NOWBOOKING BUS THING IS DONE NOW LET'S MOVE TO PAYMENT SYSTEM
CREATE TABLE Payments(
    id INT AUTO_INCREMENT PRIMARY KEY,
    amountPaid DECIMAL(10,2),
    paymentStatus VARCHAR(255) NOT NULL
);
-- PAYMENTS TABLE IS DONE
