use bus_booking2;

CREATE TABLE Users(
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(50) UNIQUE NOT NULL
);
-- USER TABLE CREATED NOW LET'S MOVE TO THE BUS  SINCE WE ONLY NEED TO PERFORM
-- OPERATION ON USER AND BUS FOR NOW

CREATE TABLE Buses(
    id INT AUTO_INCREMENT PRIMARY KEY,
    busNumber VARCHAR(50) UNIQUE NOT NULL,
    totalSeats INT NOT NULL,
    seatAvailable INT NOT NULL
);
-- NOW BUS SCHEMA IS ALSO DONE LET'S LEAVE PAYMENTS AND BOOKING TABLE FOR NOW
